[project]
authors = ["Caitlin Adams <25995927+caitlinadams@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "cdse-odata"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
ipykernel = ">=6.29.5,<7"
pyyaml = ">=6.0.2,<7"
requests = ">=2.32.3,<3"
